-- ============================================================================
-- ONE-TIME BACKFILL: populate members.aliases from parser-collected mappings
-- ============================================================================
-- Background:
--   members.username is keyed on whatever Instagram put in sender_name (mostly
--   display names like "Miles"). Handles like "mileskuzz2026" only ever
--   appeared inside system-event content strings, never in members.username.
--   So these mappings are aliases (additional names this person is known by),
--   not bio_name (a separate display-name field).
--
-- These 124 (display_name, handle) pairs were extracted by parser.py
-- from system events with >=3 observations and >=80% dominance. High confidence.
--
-- Behavior:
--   * Joins on display_name -> matches the existing members row.
--   * Appends handle to the aliases array IF it isn't already present.
--   * Idempotent — re-running won't duplicate aliases.
--   * Mappings whose display_name isn't in members are silently no-op'd.
-- ============================================================================

WITH new_aliases (display_name, handle) AS (
  VALUES
  ('𝑨𝒍𝒆𝒙♀ ☽𓃠𓆙𓆣𓆈🇲🇽', 'biitchfacemcgee'),
  ('Analiz', 'sail_boats0'),
  ('bhristopher', 'chrisspalt'),
  ('Chris ♱', '619osuna'),
  ('Dakota', 'dkfl.moto'),
  ('Kelli Richard🪻📖🦊⚔️', 'pepper_dr.pepper'),
  ('Kris10', 'okimagnome'),
  ('Chase Jordan', 'chasejordan28'),
  ('Oliver', 'olivergymo'),
  ('Miles', 'mileskuzz2026'),
  ('Sean Petit', 'mr_sean_petit_man'),
  ('verr!!! (^ v ^)', 'verrveronikak'),
  ('Jacob 😨', 'chacobov'),
  ('quynh :P', 'heartsforcatboys'),
  ('Johnny Colling', 'johnnyscollingyou'),
  ('BCMM0405', 'bcmm05'),
  ('Hayes𓆟', 'daisy.dumbass'),
  ('johanna ⋆｡˚ ☁︎ ˚｡⋆｡', 'johannapurdom'),
  ('yoni', 'nini__idk'),
  ('Eddie', 'wanpo0'),
  ('Yona', 'rip_yona_'),
  ('Fevin Kinnerty', 'fvinknerty'),
  ('Spencer', 'mathematicalmayhem'),
  ('7assouneh 🛡️', 'hsnh.72'),
  ('Tuff', 'goatedpageong'),
  ('kjelbi', 'kje.lbi'),
  ('𝐴𝑛𝑡𝑜𝑛𝑖𝑎 𝑆.', 'i2105w'),
  ('bella', 'bellamike566'),
  ('carmen *̩̩̥͙˚̩̥̩̥*̩̩͙‧͙', 'carmphobia'),
  ('xviz', 'iixvizii'),
  ('Schizophrenic', 'schizo.11'),
  ('Jaime', 'jaime.p1120'),
  ('Chels🐙🪼🐈‍⬛🦦', 'vdeadgrrrl_333'),
  ('Kaleb', 'kaleb.270'),
  ('san', 'dearly.san'),
  ('cumbersome', 'dixie_hugh420'),
  ('morky', 'morkcartney'),
  ('Amie', 'herheartrests'),
  ('dior', 'anarclitst'),
  ('release', 'darksugarfartt54'),
  ('⊹ ࣪ ˖ sara', 'saraalrkb'),
  ('kat ⪩. .⪨ 𝜗𝜚₊˚', 'p1neconesrule'),
  ('LVAG', 'mb_bhk'),
  ('gabby🍰', 'g0ob__'),
  ('Izara O M Chon', 'izara._.c'),
  ('Vervan Wildflower', '_we_are_the_gamers'),
  ('sav 🪼', 'detoxafital'),
  ('Age Of Cumquest', 'age.of.cumquest_'),
  ('McRibLover46', 'spaceboy898'),
  ('Monz (trailer park wizard)', 'arizonacoyoteist'),
  ('Stef', 'hikikomoriceo'),
  ('stupid', 'your_buddy_eric1'),
  ('Thomas', 'spilled_milk420'),
  ('𝒊𝒈𝒏𝒂𝒄𝒊𝒐', 'fr1edlegumes2go'),
  ('elicia', 'puke_ur_gutz'),
  ('mateja milenković', 'matarakados'),
  ('Kevin Finnerty', 'kvinfnerty'),
  ('The Presidential Gc', 'flix_presgc'),
  ('Juhh', 'juhh_international'),
  ('Tonito', 'tonito2597'),
  ('Loz', 'art_lozz_'),
  ('Owen Etterman', 'owen.ette'),
  ('adam 🕸️', 'ece2'),
  ('SrdjanMomcilov', 'justsrdjo'),
  ('eli', 'eli._vain'),
  ('Netflixian News', 'netflixiannews_'),
  ('༺𓆩❦𓆪༻ ri', '3cheers4nix'),
  ('Lucius Archer', 'lucius.archer'),
  ('ms. information', 'garlicksalt'),
  ('Erubiel leal', 'eru.leal'),
  ('Brandon', 'littlefuckinggreenbird'),
  ('⠀', 'c_i__c_i_'),
  ('Reece', 'i_eat_snails_69'),
  ('…', 'xxoiozanx'),
  (':3', 'childrnofthekorn'),
  ('Jar Man • 🫙👨', 'jarr.mannv2'),
  ('xj', 'wuufiy'),
  ('Emery', 'gleamingfoot644'),
  ('jin', 'zenin_jin'),
  ('Roberto Espinosa', 'squeebsqueeble'),
  ('yaz', 'notlikeyazan'),
  ('(°ロ°)', 'who_made_fun_of_my_balls'),
  ('𖤝', 'sunv4mps'),
  ('Mike Boyle', 'mikeyboyle__'),
  ('☆ cambria', 'cyb3rsirens'),
  ('haili ✞︎', 'splarpyy'),
  ('Shayan', 'officialbananaking'),
  ('fuJOshi', 'j0.is.a.l0s3r'),
  ('Sean Bonn', 'seanboi38'),
  ('xanfber', 'xandhrhrw'),
  ('Wyatt Schellhas', 'wyattschellhasiscool'),
  ('Ashlynn', 'fli.xanity'),
  ('Sara🪉', 'sararawrawr._'),
  ('Henry M', 'j.t.doggzone'),
  ('Zackary', 'frozen_.coke'),
  ('monkey D ⚔️', 'tahmudun'),
  ('Tyler Easter', 'eeeeeaster'),
  ('Duncan Barrus', 'lil_duncs_thicc_chuncs'),
  ('Kaden K', 'gir_luvs_glass'),
  ('rob', 'rob_standen_'),
  ('terroir', 'terroirannihilation'),
  ('Liz Hawkins:)', 'elizabeth_the_graceful'),
  ('emely 🐾', 'tobiluchiis'),
  ('Jack Warmelink', 'jack.warme'),
  ('simy graus', 'simy_graus'),
  ('mattie mcready', 'mattiemcready'),
  ('ella 𓆣', 'ellabrianne2'),
  ('Sponglebop pobsicle', 'deutschlandenjoyer'),
  ('Panic', 'youdownbutweup'),
  ('♫⃠Ⓐ//Ⓔ禅', 'smashdivisi0ns'),
  ('falak', 'takesme2xantopassout'),
  ('𝑴𝒊𝒄𝒉𝒂𝒆𝒍', 'bladedriver2049'),
  ('g', 'similetaphor'),
  ('S S', 'smband.z'),
  ('Docta', 'docta_gio2.0'),
  ('Travis Tilley', 'travislord304'),
  ('Bread', 'breadulous123'),
  ('kieran', 'kieranduong_'),
  ('me i guess', 'sinongbakla'),
  ('Owen Kuhn', 'owennkuhnn'),
  ('MacKay Brendle', 'mackaybrendle'),
  ('Rory', 'de4th_2rory'),
  ('chepecultz𓁷', 'allstvrchepe'),
  ('Big A.L', 'dandysandwigger')
)
UPDATE members m
   SET aliases    = array_append(m.aliases, na.handle),
       updated_at = NOW()
  FROM new_aliases na
 WHERE m.username = na.display_name
   AND NOT (na.handle = ANY(m.aliases))
RETURNING m.username, m.aliases;
